# Dev environment: 1 replica
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftm-backend
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftm-frontend
spec:
  replicas: 1
