apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-docker
  labels:
    jenkins: agent
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    args:
      - '$(JENKINS_SECRET)'
      - '$(JENKINS_NAME)'
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "2000m"
  
  - name: docker
    image: docker:dind
    securityContext:
      privileged: true
    volumeMounts:
      - name: docker-graph-storage
        mountPath: /var/lib/docker
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
  
  - name: dotnet
    image: mcr.microsoft.com/dotnet/sdk:7.0
    command:
      - sleep
    args:
      - "99999"
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
  
  - name: kubectl
    image: bitnami/kubectl:latest
    command:
      - sleep
    args:
      - "99999"
  
  volumes:
    - name: docker-graph-storage
      emptyDir: {}
